import {
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
} from '@radix-ui/react-icons';
import {
  BetweenHorizonalEnd,
  BetweenHorizonalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  Bold,
  BookMarked,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Clipboard,
  Code,
  CodeXml,
  Columns2,
  Columns3,
  Columns4,
  Copy,
  CropIcon,
  Eraser,
  Eye,
  FlipHorizontal,
  FlipVertical,
  Frame,
  GripVertical,
  Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  ImageUp,
  IndentDecrease,
  IndentIncrease,
  Italic,
  Link,
  List,
  ListOrdered,
  ListTodo,
  LoaderCircle,
  Maximize,
  Minimize,
  Minus,
  PaintRoller,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Plus,
  Quote,
  Redo2,
  Replace,
  Settings,
  Sigma,
  SmilePlus,
  SmilePlusIcon,
  Sparkles,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCellsMerge,
  TableCellsSplit,
  Trash,
  Trash2,
  Type,
  Underline,
  Undo2,
  Unlink,
  Video,
  ZoomIn,
  ZoomOut,
  PencilRuler,
  WrapText,
  Loader2 as Loader,
  X,
  ExternalLink
} from 'lucide-react';

import {
  AspectRatio,
  BlockquoteLeft,
  DeleteColumn,
  DeleteRow,
  FileWordOutline,
  FormatLineHeight,
  MenuDown,
  SizeL,
  SizeM,
  SizeS,
} from '@editor-v2/components/icons';
import { CodeView } from '@editor-v2/components/icons/CodeView';
import { ColumnAddLeft } from '@editor-v2/components/icons/ColumnAddLeft';
import { ColumnAddRight } from '@editor-v2/components/icons/ColumnAddRight';
import { Direction } from '@editor-v2/components/icons/Direction';
import { Excalidraw } from '@editor-v2/components/icons/Excalidraw';
import { ExportPdf } from '@editor-v2/components/icons/ExportPdf';
import ExportWord from '@editor-v2/components/icons/ExportWord';
import { GifIcon } from '@editor-v2/components/icons/GIfIcon';
import { Html } from '@editor-v2/components/icons/Html';
import { LeftToRight } from '@editor-v2/components/icons/LeftToRight';
import { Mermaid } from '@editor-v2/components/icons/Mermaid';
import { RightToLeft } from '@editor-v2/components/icons/RightToLeft';
import { Twitter } from '@editor-v2/components/icons/Twitter';

import ImportWord from './ImportWord';

export const icons = {
  Bold,
  LoaderCircle,
  Italic,
  Underline,
  Quote,
  TextQuote: BlockquoteLeft,
  Strikethrough,
  Minus,
  Eraser,
  PaintRoller,
  Redo2,
  Undo2,
  AlignCenter: TextAlignCenterIcon,
  AlignJustify: TextAlignJustifyIcon,
  AlignLeft: TextAlignLeftIcon,
  AlignRight: TextAlignRightIcon,
  ChevronDown,
  Subscript,
  Superscript,
  Code,
  Code2: CodeXml,
  Type,
  IndentIncrease,
  IndentDecrease,
  List,
  ListOrdered,
  ListTodo,
  Link,
  ImageUp,
  Video,
  Maximize,
  Minimize,
  Table,
  Sparkles,
  Pencil,
  Unlink,
  BetweenHorizonalEnd,
  BetweenHorizonalStart,
  BetweenVerticalStart,
  BetweenVerticalEnd,
  TableCellsMerge,
  TableCellsSplit,
  Trash2,
  Trash,
  Replace,
  ChevronsUpDown,
  LineHeight: FormatLineHeight,
  Word: FileWordOutline,
  HeadingParagraph: Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Columns2,
  Columns3,
  Columns4,
  Plus,
  Grip: GripVertical,
  Copy,
  Clipboard,
  PanelLeft,
  PanelRight,
  Columns: Columns2,
  Iframe: Frame,

  MenuDown,
  SizeS,
  SizeM,
  SizeL,
  AspectRatio,

  Emoji: SmilePlus,

  DeleteColumn,
  DeleteRow,
  SearchAndReplace: Replace,
  EmojiIcon: SmilePlusIcon,
  KatexIcon: Sigma,
  ExportPdf,
  ExportWord,
  ImportWord,
  ColumnAddLeft,
  ColumnAddRight,
  BookMarked,
  Excalidraw,
  ZoomIn,
  ZoomOut,
  Settings,
  Eye,

  TextDirection: Direction,
  LeftToRight,
  RightToLeft,

  Attachment: Paperclip,
  GifIcon,
  ChevronUp,
  Crop: CropIcon,
  Mermaid,
  Twitter,
  CodeView,
  FlipX: FlipVertical,
  FlipY: FlipHorizontal,
  PencilRuler,
  WrapText,
  Loader,
  X,
  Html,
  ExternalLink
} as any;

